### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [4]:
import numpy as np

vector = np.random.rand(1, 10)

print(vector)

[[0.56630103 0.03259614 0.94643377 0.12739887 0.16704658 0.84445072
  0.11951102 0.85019157 0.96196761 0.36856721]]


In [7]:
import numpy as np

matrix = np.array ([[11, 14, 17],
                   [20, 23, 26],
                   [29, 32, 25]])

print(matrix)

[[11 14 17]
 [20 23 26]
 [29 32 25]]


In [36]:
print("Розмір вектора:", vector.shape)
print("Розмір матриці:", matrix.shape)

Розмір вектора: (1, 10)
Розмір матриці: (3, 3)



### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [1]:
import numpy as np

vector = np.array ([[0.56630103, 0.03259614, 0.94643377, 0.12739887, 0.16704658, 0.84445072,
  0.11951102, 0.85019157, 0.96196761, 0.36856721],
                    ])
vector_10 = vector + 10

print(np.round(vector_10, 2))

[[10.57 10.03 10.95 10.13 10.17 10.84 10.12 10.85 10.96 10.37]]


In [2]:
import numpy as np

matrix = np.array ([[11, 14, 17],
                   [20, 23, 26],
                   [29, 32, 25]])

matrix_2 = matrix * 2

print(matrix_2)

[[22 28 34]
 [40 46 52]
 [58 64 50]]


In [4]:
import numpy as np

vector = np.array ([[0.56630103, 0.03259614, 0.94643377, 0.12739887, 0.16704658, 0.84445072,
  0.11951102, 0.85019157, 0.96196761, 0.36856721],
                    ])

vector_squared = vector ** 2

print(vector_squared)

[[0.32069686 0.00106251 0.89573688 0.01623047 0.02790456 0.71309702
  0.01428288 0.72282571 0.92538168 0.13584179]]



### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [6]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

result_matrix = np.dot(A, B)

#C = np.array([[0], [1]])

#D = np.array([[0,1], [1,0]])

#C_mult_v = np.dot(result_matrix, C)
#D_mult_v = np.dot(result_matrix, D)

display(A, B, C, D)
print(result_matrix)
#print(C_mult_v)
#print(D_mult_v)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

[[0.232  0.1627 0.2145]
 [0.3061 0.4867 0.633 ]
 [0.1393 0.2261 0.294 ]]



### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [32]:
result_matrix_T = result_matrix.T

print(result_matrix_T)

[[0.232  0.3061 0.1393]
 [0.1627 0.4867 0.2261]
 [0.2145 0.633  0.294 ]]


In [33]:
vector_T = vector.T

print(vector_T)

[[0.56630103]
 [0.03259614]
 [0.94643377]
 [0.12739887]
 [0.16704658]
 [0.84445072]
 [0.11951102]
 [0.85019157]
 [0.96196761]
 [0.36856721]]


In [34]:
column_vector = np.expand_dims(vector, axis=1)

print(vector)
print(column_vector)

[[0.56630103 0.03259614 0.94643377 0.12739887 0.16704658 0.84445072
  0.11951102 0.85019157 0.96196761 0.36856721]]
[[[0.56630103 0.03259614 0.94643377 0.12739887 0.16704658 0.84445072
   0.11951102 0.85019157 0.96196761 0.36856721]]]


In [35]:
column_vector_T = column_vector.T

print(column_vector_T)

[[[0.56630103]]

 [[0.03259614]]

 [[0.94643377]]

 [[0.12739887]]

 [[0.16704658]]

 [[0.84445072]]

 [[0.11951102]]

 [[0.85019157]]

 [[0.96196761]]

 [[0.36856721]]]
